import crypto from "node:crypto";
import nodemailer from "nodemailer";
import { pool } from "./db.js";
import { decrypt } from "./security.js";
import dns from "node:dns/promises";
import net from "node:net";

export async function settings(){const q=await pool.query("select key,value,secret from app_settings");return Object.fromEntries(q.rows.map(r=>[r.key,r.secret&&r.value?.encrypted?decrypt(r.value.encrypted):r.value]));}
export async function sendMail(to:string|string[],subject:string,text:string){const s=await settings();if(!s.smtp_host)throw new Error("SMTP is not configured");const transport=nodemailer.createTransport({host:String(s.smtp_host),port:Number(s.smtp_port||587),secure:Boolean(s.smtp_secure),auth:s.smtp_user?{user:String(s.smtp_user),pass:String(s.smtp_password||"")}:undefined});return transport.sendMail({from:String(s.smtp_from||"SignalDesk <noreply@example.com>"),to,subject,text});}
export async function deliverAuthEmail(email:string,kind:string,token:string){const base=process.env.APP_URL||"http://localhost:3000";const paths:Record<string,string>={verify:"verify-email",reset:"reset-password",magic:"magic-login",email_change:"confirm-email"};const link=`${base}/${paths[kind]}?token=${encodeURIComponent(token)}`;if(process.env.NODE_ENV!=="production"&&!process.env.SMTP_HOST){console.log(JSON.stringify({event:"auth_email",kind,email,link}));return;}await sendMail(email,`SignalDesk ${kind.replace("_"," ")}`,`Open this secure link to continue: ${link}\n\nThis link expires automatically.`);}

export async function aiConfig(){const s=await settings();return {accountId:String(s.cf_account_id||process.env.CLOUDFLARE_ACCOUNT_ID||""),gatewayId:String(s.cf_gateway_id||process.env.CLOUDFLARE_GATEWAY_ID||"default"),token:String(s.cf_api_token||process.env.CLOUDFLARE_API_TOKEN||""),generationModel:String(s.generation_model||"openai/gpt-5.6-luna"),embeddingModel:String(s.embedding_model||"@cf/qwen/qwen3-embedding-0.6b")};}
export async function generateJson<T>(instructions:string,input:string,fallback:T):Promise<{data:T;model:string;usage:{input:number;output:number}}>{const c=await aiConfig();if(!c.accountId||!c.token)return {data:fallback,model:"demo",usage:{input:0,output:0}};const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${c.accountId}/ai/v1/responses`,{method:"POST",headers:{Authorization:`Bearer ${c.token}`,"cf-aig-gateway-id":c.gatewayId,"Content-Type":"application/json","cf-aig-metadata":JSON.stringify({app:"signaldesk"})},body:JSON.stringify({model:c.generationModel,instructions,input,text:{format:{type:"json_object"}}})});if(!response.ok)throw new Error(`AI generation failed (${response.status})`);const json:any=await response.json();const text=json.output_text||json.result?.output_text||json.output?.flatMap((x:any)=>x.content||[]).find((x:any)=>x.type==="output_text")?.text;if(!text)throw new Error("AI returned no structured output");return {data:JSON.parse(text),model:c.generationModel,usage:{input:json.usage?.input_tokens||0,output:json.usage?.output_tokens||0}};}
export async function embed(text:string){const c=await aiConfig();if(!c.accountId||!c.token)return null;const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${c.accountId}/ai/run`,{method:"POST",headers:{Authorization:`Bearer ${c.token}`,"cf-aig-gateway-id":c.gatewayId,"Content-Type":"application/json"},body:JSON.stringify({model:c.embeddingModel,input:{text:[text]}})});if(!response.ok)throw new Error(`Embedding failed (${response.status})`);const json:any=await response.json();return {vector:json.result?.data?.[0]||json.result?.[0]||json.data?.[0]?.embedding,model:c.embeddingModel};}
export const id=()=>crypto.randomUUID();
export async function assertPublicUrl(value:string,expectedHost?:string){const url=new URL(value);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new Error("Only public HTTP(S) URLs are allowed.");if(expectedHost&&url.hostname.toLowerCase()!==expectedHost.toLowerCase())throw new Error("Crawl URL must stay on the project host.");const addresses=await dns.lookup(url.hostname,{all:true});for(const {address} of addresses){if(net.isIP(address)===4&&(/^(127\.|10\.|192\.168\.|169\.254\.)/.test(address)||/^172\.(1[6-9]|2\d|3[01])\./.test(address)))throw new Error("Private network URLs are not allowed.");if(net.isIP(address)===6&&(address==="::1"||address.startsWith("fc")||address.startsWith("fd")||address.startsWith("fe80")))throw new Error("Private network URLs are not allowed.");}return url}
