import { pool,migrate } from "./db.js";
import { generateJson,sendMail,id,embed,assertPublicUrl } from "./services.js";
import { decrypt } from "./security.js";
import crypto from "node:crypto";
const workerId=`worker-${process.pid}`;

async function enqueueDue(){await pool.query(`insert into jobs(id,kind,payload) select gen_random_uuid(),'generate_due',jsonb_build_object('scheduledItemId',s.id) from scheduled_items s join projects p on p.id=s.project_id join organizations o on o.id=p.organization_id join plans pl on pl.id=o.plan_id where s.status='scheduled' and p.active and (o.subscription_status='active' or (o.subscription_status='trialing' and o.current_period_end>now()) or (o.subscription_status='past_due' and o.current_period_end+make_interval(days=>pl.grace_days)>now())) and s.scheduled_for>=date_trunc('day',now()) and s.scheduled_for<=now() and not exists(select 1 from jobs j where j.payload->>'scheduledItemId'=s.id::text and j.status in ('queued','running','complete'))`)}
async function claim(){return (await pool.query(`update jobs set status='running',locked_at=now(),locked_by=$1,attempts=attempts+1 where id=(select id from jobs where status='queued' and run_at<=now() order by run_at for update skip locked limit 1) returning *`,[workerId])).rows[0]}
const textOnly=(html:string)=>html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
async function crawlSite(projectId:string){
 const q=await pool.query("select * from projects where id=$1 and active",[projectId]);if(!q.rowCount)return;const p=q.rows[0],origin=new URL(p.canonical_url).origin,sitemap=String(p.sitemap_urls?.[0]||`${origin}/wp-sitemap.xml`);await assertPublicUrl(sitemap,p.canonical_host);
 const mapResponse=await fetch(sitemap,{headers:{"User-Agent":"SignalDeskBot/0.2"}}),map=mapResponse.ok?await mapResponse.text():"",locs=[...map.matchAll(/<loc>\s*([^<]+)\s*<\/loc>/gi)].map(x=>x[1].replace(/&amp;/g,"&")).filter(x=>{try{return new URL(x).hostname===p.canonical_host}catch{return false}}).slice(0,200),urls=locs.length?locs:[p.canonical_url];
 for(const value of urls){await assertPublicUrl(value,p.canonical_host);const response=await fetch(value,{headers:{"User-Agent":"SignalDeskBot/0.2"}});if(!response.ok)continue;const html=await response.text(),body=textOnly(html),title=(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"").trim(),contentHash=crypto.createHash("sha256").update(body).digest("hex"),existing=await pool.query("select id,content_hash from crawled_pages where project_id=$1 and canonical_url=$2",[p.id,value]);if(existing.rows[0]?.content_hash===contentHash)continue;const pageId=existing.rows[0]?.id||id();await pool.query(`insert into crawled_pages(id,project_id,url,canonical_url,title,body,content_hash,indexed_at) values($1,$2,$3,$3,$4,$5,$6,now()) on conflict(project_id,canonical_url) do update set title=excluded.title,body=excluded.body,content_hash=excluded.content_hash,indexed_at=now(),updated_at=now()`,[pageId,p.id,value,title,body,contentHash]);await pool.query("delete from content_chunks where page_id=$1",[pageId]);const chunks=body.match(/[\s\S]{1,2800}(?:\s|$)/g)||[];for(let n=0;n<chunks.length;n++){const vector=await embed(chunks[n]);await pool.query("insert into content_chunks(id,project_id,page_id,content,ordinal,embedding,embedding_model) values($1,$2,$3,$4,$5,$6::vector,$7)",[id(),p.id,pageId,chunks[n],n,vector?.vector?JSON.stringify(vector.vector):null,vector?.model||null])}}
 await pool.query("update projects set embedding_status='ready',embedding_model=(select embedding_model from content_chunks where project_id=$1 and embedding_model is not null limit 1),updated_at=now() where id=$1",[p.id]);
}
async function processItem(job:any){
 const q=await pool.query(`select s.*,p.name project_name,p.audience,p.offer,p.tone,p.publish_mode,p.notification_emails,p.notify_on_publish,p.connector_site,p.active project_active,o.subscription_status,o.current_period_end,pl.grace_days from scheduled_items s join projects p on p.id=s.project_id join organizations o on o.id=p.organization_id join plans pl on pl.id=o.plan_id where s.id=$1`,[job.payload.scheduledItemId]);if(!q.rowCount)return;const item=q.rows[0],periodEnd=new Date(item.current_period_end).getTime(),planActive=item.subscription_status==="active"||(item.subscription_status==="trialing"&&periodEnd>Date.now())||(item.subscription_status==="past_due"&&periodEnd+Number(item.grace_days)*86400_000>Date.now());if(!item.project_active||!planActive){await pool.query("update scheduled_items set status='failed',last_error=$2,updated_at=now() where id=$1",[item.id,!item.project_active?"Project disabled by the current plan.":"Article generation requires an active plan."]);return;}
 await pool.query("update scheduled_items set status='generating',locked_at=now(),attempts=attempts+1 where id=$1 and status in ('scheduled','failed')",[item.id]);
 const chunks=await pool.query("select heading,content from content_chunks where project_id=$1 order by created_at desc limit 12",[item.project_id]);
 const fallback={title:item.title,content:`<!-- wp:heading --><h2>${item.title}</h2><!-- /wp:heading --><!-- wp:paragraph --><p>This draft was prepared from the saved context for ${item.project_name}. Add verified examples and sources before publishing.</p><!-- /wp:paragraph -->`,citations:[],internalLinks:[]};
 const context=chunks.rows.map((x:any)=>`${x.heading||"Page"}: ${x.content}`).join("\n").slice(0,30000),result=await generateJson<any>("Write a people-first, source-conscious WordPress article as Gutenberg block HTML. Never invent statistics. Return JSON with title, content, citations array, and internalLinks array.",`Project: ${item.project_name}\nAudience: ${item.audience}\nOffer: ${item.offer}\nVoice: ${item.tone}\nTopic: ${item.title}\nExisting excerpts:\n${context}`,fallback);
 const version=(await pool.query("select coalesce(max(version),0)+1 version from article_versions where scheduled_item_id=$1",[item.id])).rows[0].version,versionId=id();
 await pool.query("insert into article_versions(id,scheduled_item_id,version,title,content,citations,internal_links,model,input_tokens,output_tokens) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)",[versionId,item.id,version,result.data.title,result.data.content,JSON.stringify(result.data.citations||[]),JSON.stringify(result.data.internalLinks||[]),result.model,result.usage.input,result.usage.output]);
 let wp:any=null;if(item.connector_site?.endpoint&&item.connector_site?.tokenEncrypted){const idem=`${item.id}:${version}`,response=await fetch(`${String(item.connector_site.endpoint).replace(/\/$/,"")}/wp-json/signaldesk/v1/drafts`,{method:"POST",headers:{"Content-Type":"application/json","X-SignalDesk-Token":decrypt(String(item.connector_site.tokenEncrypted)),"Idempotency-Key":idem},body:JSON.stringify({title:result.data.title,content:result.data.content,status:item.publish_mode,external_id:item.id})});wp=await response.json().catch(()=>({}));await pool.query("insert into publication_attempts(id,scheduled_item_id,article_version_id,idempotency_key,attempt,status,response,error) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(idempotency_key) do nothing",[id(),item.id,versionId,idem,item.attempts+1,response.ok?"complete":"failed",JSON.stringify(wp),response.ok?null:`WordPress ${response.status}`]);if(!response.ok)throw new Error(`WordPress publishing failed (${response.status})`)}
 const final=item.publish_mode==="publish"?"published":"drafted";await pool.query("update scheduled_items set status=$1,last_error=null,updated_at=now() where id=$2",[final,item.id]);if(item.notify_on_publish&&item.notification_emails?.length)await sendMail(item.notification_emails,`${result.data.title} was ${final}`,`SignalDesk ${final} the scheduled article for ${item.project_name}.${wp?.edit_url?`\n\nEdit: ${wp.edit_url}`:""}`);
}
async function run(job:any){try{if(job.kind==="generate_due")await processItem(job);if(job.kind==="crawl_site")await crawlSite(job.payload.projectId);await pool.query("update jobs set status='complete',completed_at=now() where id=$1",[job.id])}catch(e){const message=e instanceof Error?e.message:String(e);if(job.attempts<job.max_attempts)await pool.query("update jobs set status='queued',run_at=now()+($2||' minutes')::interval,error=$3,locked_at=null,locked_by=null where id=$1",[job.id,String(2**job.attempts),message]);else{await pool.query("update jobs set status='failed',error=$2 where id=$1",[job.id,message]);if(job.payload.scheduledItemId)await pool.query("update scheduled_items set status='failed',last_error=$2 where id=$1",[job.payload.scheduledItemId,message])}}}
async function tick(){await enqueueDue();const job=await claim();if(job)await run(job)}
export async function startWorker(){await migrate();console.log(JSON.stringify({event:"worker_started",workerId}));setInterval(()=>tick().catch(e=>console.error(JSON.stringify({event:"worker_tick_failed",message:e.message}))),5000);await tick()}
if(process.env.NODE_ENV!=="test")startWorker().catch(e=>{console.error(e);process.exit(1)});
