async function request<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(path,{...options,credentials:"same-origin",headers:{"Content-Type":"application/json",...options.headers}});if(response.status===204)return undefined as T;const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||`Request failed (${response.status})`);return body as T}
const json=(method:string,data?:unknown):RequestInit=>({method,body:data===undefined?undefined:JSON.stringify(data)});
export const api={
 changeEmail:(currentPassword:string,newEmail:string)=>request<any>("/api/me/email",json("PUT",{currentPassword,newEmail})),
 adminPlans:()=>request<any[]>("/api/admin/plans"),savePlans:(plans:unknown[])=>request("/api/admin/plans",json("PUT",{plans})),syncStripe:()=>request<any>("/api/admin/stripe/sync",json("POST")),
 me:()=>request<any>("/api/me"),changePassword:(currentPassword:string,newPassword:string)=>request("/api/me/password",json("PUT",{currentPassword,newPassword})),login:(data:unknown)=>request("/api/auth/login",json("POST",data)),register:(data:unknown)=>request<any>("/api/auth/register",json("POST",data)),magic:(email:string)=>request<any>("/api/auth/magic",json("POST",{email})),consume:(token:string,kind:string)=>request("/api/auth/consume",json("POST",{token,kind})),forgot:(email:string)=>request<any>("/api/auth/forgot",json("POST",{email})),reset:(token:string,password:string)=>request("/api/auth/reset",json("POST",{token,password})),logout:()=>request("/api/auth/logout",json("POST")),
 organization:(id:string)=>request<any>(`/api/organizations/${id}`),createProject:(data:unknown)=>request<any>("/api/projects",json("POST",data)),project:(id:string)=>request<any>(`/api/projects/${id}`),saveProject:(id:string,data:unknown)=>request(`/api/projects/${id}`,json("PUT",data)),pairToken:(id:string)=>request<any>(`/api/projects/${id}/site/pair-token`,json("POST")),crawl:(id:string)=>request<any>(`/api/projects/${id}/site/crawl`,json("POST")),calendar:(id:string,month:string,count:number)=>request<any>(`/api/projects/${id}/calendar/generate`,json("POST",{month,count})),updateItem:(id:string,data:unknown)=>request(`/api/content/${id}`,json("PATCH",data)),retry:(id:string)=>request(`/api/content/${id}/retry`,json("POST")),
 admin:()=>request<any>("/api/admin/overview"),adminSettings:()=>request<any[]>("/api/admin/settings"),saveSettings:(entries:unknown[])=>request("/api/admin/settings",json("PUT",{entries})),testService:(service:string)=>request(`/api/admin/test/${service}`,json("POST")),billingPortal:(org:string)=>request<any>(`/api/billing/${org}/portal`,json("POST")),checkout:(org:string,plan:string)=>request<any>(`/api/billing/${org}/checkout`,json("POST",{plan}))
};
