import { useEffect,useMemo,useState } from "react";
import { api } from "./api";
import type { CalendarItem,Me,Project } from "./types";

const go=(path:string)=>{history.pushState({}, "",path);dispatchEvent(new PopStateEvent("popstate"))};
function Brand(){return <button className="brand brand-button" onClick={()=>go("/dashboard")}>SignalDesk<span>β</span></button>}
function Notice({value}:{value:string}){return value?<p className="notice" role="status">{value}</p>:null}
function BusyLabel({busy,label}:{busy:boolean;label:string}){return <>{busy&&<span className="button-spinner" aria-hidden="true"/>}{label}</>}

function Auth({mode}:{mode:"login"|"register"|"forgot"|"reset"}){
 const [form,setForm]=useState({name:"",organizationName:"",email:"",password:""}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const token=new URLSearchParams(location.search).get("token")||"";
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{if(mode==="login"){await api.login(form);location.href="/dashboard"}else if(mode==="register"){const r=await api.register(form);setMessage(r.message+(r.developmentToken?` Development token: ${r.developmentToken}`:""))}else if(mode==="forgot")setMessage((await api.forgot(form.email)).message);else{await api.reset(token,form.password);setMessage("Password changed. You can sign in now.")}}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 const magic=async()=>{setBusy(true);try{setMessage((await api.magic(form.email)).message)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 return <main className="auth-page"><div className="auth-mark"><Brand/><p>Search growth, with a paper trail.</p></div><section className="auth-card"><p className="utility">{mode==="register"?"Start a workspace":"Welcome back"}</p><h1>{mode==="login"?"Open your publishing desk.":mode==="register"?"Build your first search calendar.":mode==="forgot"?"Reset your password.":"Choose a new password."}</h1><form onSubmit={submit}>
 {mode==="register"&&<><label>Your name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Organization<input required value={form.organizationName} onChange={e=>setForm({...form,organizationName:e.target.value})}/></label></>}
 {mode!=="reset"&&<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>}
 {!["forgot"].includes(mode)&&<label>Password<input required type="password" minLength={10} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}
 <button className="button" disabled={busy} aria-busy={busy}><BusyLabel busy={busy} label={busy?"Working…":mode==="login"?"Sign in":mode==="register"?"Create workspace":mode==="forgot"?"Send reset link":"Save new password"}/></button>
 </form>{mode==="login"&&<button className="button button-quiet" disabled={!form.email||busy} onClick={magic}>Email me a sign-in link</button>}<Notice value={message}/><div className="auth-links">{mode==="login"?<><button onClick={()=>go("/register")}>Create account</button><button onClick={()=>go("/forgot-password")}>Forgot password?</button></>:<button onClick={()=>go("/login")}>Back to sign in</button>}</div></section></main>
}

function Shell({me,children,active,orgId}:{me:Me;children:React.ReactNode;active:string;orgId?:string}){
 const canAdmin=["super_admin","moderator"].includes(me.user.platformRole),org=me.organizations.find(o=>o.id===orgId),canBill=org?.role==="owner"||me.user.platformRole==="super_admin";return <div className="app-shell"><header className="topbar"><Brand/><div className="account-chip"><span>{me.user.name}</span><small>{me.user.email}</small></div></header><aside className="rail"><nav><button className={active==="dashboard"?"active":""} onClick={()=>go("/dashboard")}>Overview</button>{orgId&&<><button className={active==="projects"?"active":""} onClick={()=>go(`/projects?organization=${orgId}`)}>Projects</button>{canBill&&<button className={active==="billing"?"active":""} onClick={()=>go(`/billing?organization=${orgId}`)}>Billing</button>}</>}<button className={active==="settings"?"active":""} onClick={()=>go("/settings")}>Your settings</button>{canAdmin&&<button className={active==="admin"?"active":""} onClick={()=>go("/admin")}>Platform admin</button>}</nav><button className="signout" onClick={async()=>{await api.logout();location.href="/login"}}>Sign out</button></aside><main className="workbench">{children}</main></div>
}

function Dashboard({me}:{me:Me}){return <Shell me={me} active="dashboard"><header className="page-head"><div><p className="utility">Dashboard</p><h1>Your sites</h1></div><p>Manage connected sites, content calendars, and publishing.</p></header><div className="org-grid">{me.organizations.map(org=><article className="org-card" key={org.id}><div><span className="status-dot"/><small>{org.plan} · {org.subscription_status}</small></div><h2>{org.name}</h2><dl><div><dt>Projects</dt><dd>up to {org.project_limit}</dd></div><div><dt>Monthly posts</dt><dd>{org.post_limit}</dd></div><div><dt>Your role</dt><dd>{org.role}</dd></div></dl><button className="text-action" onClick={()=>go(`/projects?organization=${org.id}`)}>View projects →</button></article>)}</div></Shell>}

function Projects({me}:{me:Me}){
 const orgId=new URLSearchParams(location.search).get("organization")||me.organizations[0]?.id,[data,setData]=useState<any>(),[show,setShow]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const [form,setForm]=useState({organizationId:orgId,name:"",canonicalUrl:"",audience:"",offer:"",tone:"Clear, practical, evidence-led",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,locale:"en",publishMode:"draft",notifyOnPublish:true});
 const load=()=>api.organization(orgId).then(setData).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[orgId]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const r=await api.createProject(form);go(`/projects/${r.id}`)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};const activeCount=data?.projects?.filter((p:any)=>p.active).length||0,atLimit=data&&activeCount>=data.organization.project_limit;
 return <Shell me={me} orgId={orgId} active="projects"><header className="page-head"><div><p className="utility">Projects</p><h1>{data?.organization?.name||"Projects"}</h1></div><button className="button" disabled={atLimit} onClick={()=>setShow(!show)}>{show?"Close form":"Add project"}</button></header><Notice value={message}/>{data&&<section className="plan-summary"><div><small>Current plan</small><strong>{data.organization.plan_name} · {data.organization.subscription_status}</strong></div><div><small>Projects</small><strong>{activeCount} of {data.organization.project_limit}</strong></div><div><small>Scheduled posts</small><strong>Up to {data.organization.post_limit} / month</strong></div>{data.role==="owner"&&<button className="text-action" onClick={()=>go(`/billing?organization=${orgId}`)}>Manage plan →</button>}</section>}{show&&<form className="panel form-grid" onSubmit={create}><label>Site name<input required disabled={busy} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Canonical URL<input required disabled={busy} type="url" placeholder="https://example.com" value={form.canonicalUrl} onChange={e=>setForm({...form,canonicalUrl:e.target.value})}/></label><label>Audience<textarea required disabled={busy} value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></label><label>Offer<textarea required disabled={busy} value={form.offer} onChange={e=>setForm({...form,offer:e.target.value})}/></label><label>Writing voice<input required disabled={busy} value={form.tone} onChange={e=>setForm({...form,tone:e.target.value})}/></label><button className="button" disabled={busy} aria-busy={busy}><BusyLabel busy={busy} label={busy?"Creating project…":"Create project"}/></button></form>}<div className="project-list">{data?.projects?.map((p:any)=><button className={`project-row${p.active?"":" project-row--disabled"}`} key={p.id} onClick={()=>go(`/projects/${p.id}`)}><span><strong>{p.name}</strong><small>{p.canonical_url}</small></span><span className="project-state">{p.active?(p.connector_last_seen_at?"WordPress connected":"Website only"):`Disabled · ${p.disabled_reason==="plan_limit"?"plan limit":"inactive plan"}`}</span><b>→</b></button>)}{data&&data.projects.length===0&&<div className="empty"><h2>No projects yet</h2><p>Add a website to start planning content.</p></div>}</div></Shell>
}

function ProjectView({me,id}:{me:Me;id:string}){
 const [data,setData]=useState<{project:Project;items:CalendarItem[]}|null>(null),[message,setMessage]=useState(""),[pair,setPair]=useState<{token:string;endpoint:string}|null>(null),[busy,setBusy]=useState("");const load=()=>api.project(id).then(setData).catch(e=>setMessage(e.message));useEffect(()=>{void load()},[id]);const p=data?.project;
 const generate=async()=>{setBusy("calendar");try{const month=new Date().toISOString().slice(0,7),r=await api.calendar(id,month,Math.min(10,p?.post_limit||10));setMessage(`${r.created} calendar items created. Scores are AI estimates, not search-volume data.`);load()}catch(e){setMessage((e as Error).message)}finally{setBusy("")}};
 const pairing=async()=>{setBusy("wordpress");try{const r=await api.pairToken(id);setPair(r);setMessage("WordPress connection details created.")}catch(e){setMessage((e as Error).message)}finally{setBusy("")}};
 const counts=useMemo(()=>Object.fromEntries(["scheduled","generating","drafted","published","failed"].map(s=>[s,data?.items.filter(i=>i.status===s).length||0])),[data]);
 if(!p)return <Shell me={me} active="projects"><Notice value={message||"Loading project…"}/></Shell>;
 return <Shell me={me} orgId={p.organization_id} active="projects"><header className="page-head"><div><p className="utility">{p.organization_name}</p><h1>{p.name}</h1><a href={p.canonical_url} target="_blank">{p.canonical_url}</a></div><button className="button" disabled={busy==="calendar"||!p.active} aria-busy={busy==="calendar"} onClick={generate}><BusyLabel busy={busy==="calendar"} label={busy==="calendar"?"Building calendar…":"Build this month"}/></button></header>{!p.active&&<Notice value="This project is disabled because it exceeds the current plan allowance."/>}<Notice value={message}/><section className="instrument">{Object.entries(counts).map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</section><section className="connectors"><div className="section-head"><div><p className="utility">Connectors</p><h2>WordPress</h2><p>Connect WordPress to import existing posts and send scheduled articles back as drafts or published posts.</p></div><span className={`connector-status${p.connector_last_seen_at?" connector-status--connected":""}`}>{p.connector_last_seen_at?"Connected":"Not connected"}</span></div><button className="button button-quiet" disabled={busy==="wordpress"||!p.active} aria-busy={busy==="wordpress"} onClick={pairing}><BusyLabel busy={busy==="wordpress"} label={busy==="wordpress"?"Preparing…":p.connector_last_seen_at?"Reconnect WordPress":"Connect WordPress"}/></button>{pair&&<div className="pair-details"><p>Install the SignalDesk Connector plugin in WordPress. Under <strong>Settings → SignalDesk</strong>, paste this endpoint and token.</p><label>Endpoint<code>{pair.endpoint}</code></label><label>Pairing token<code>{pair.token}</code></label><small>The token is shown once. Creating another token revokes it.</small></div>}</section><section className="calendar-board"><div className="section-head"><div><h2>Publication calendar</h2><p>SignalDesk generates each article on its scheduled date.</p></div></div>{data.items.map(item=><article className="calendar-row" key={item.id}><time>{new Date(item.scheduled_for).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time><div><span className={`status status--${item.status}`}>{item.status}</span><h3>{item.title}</h3><p>{item.keyword} · {item.intent} intent · priority {item.priority}/100</p>{item.last_error&&<small className="error">{item.last_error}</small>}</div>{item.status==="failed"?<button onClick={async()=>{await api.retry(item.id);load()}}>Retry</button>:<button onClick={async()=>{await api.updateItem(item.id,{status:"skipped"});load()}}>Skip</button>}</article>)}{!data.items.length&&<div className="empty"><h2>No articles scheduled</h2><p>Build this month to add topics to the calendar.</p></div>}</section></Shell>
}

function Billing({me}:{me:Me}){const orgId=new URLSearchParams(location.search).get("organization")||me.organizations[0]?.id,org=me.organizations.find(x=>x.id===orgId),[message,setMessage]=useState("");const checkout=async(plan:string)=>{try{const r=await api.checkout(orgId,plan);location.href=r.url}catch(e){setMessage((e as Error).message)}};return <Shell me={me} orgId={orgId} active="billing"><header className="page-head"><div><p className="utility">Billing</p><h1>{org?.name}</h1></div><span className="plan-stamp">{org?.plan} · {org?.subscription_status}</span></header><Notice value={message}/><div className="plan-grid">{[["starter",1,10],["growth",5,50],["agency",25,250]].map(([name,projects,posts])=><article className="plan-card" key={String(name)}><small>{String(name)}</small><h2>{posts} posts</h2><p>{projects} connected {Number(projects)===1?"site":"sites"} per month.</p><button className="button" onClick={()=>checkout(String(name))}>Choose {String(name)}</button></article>)}</div><button className="text-action" onClick={async()=>{try{const r=await api.billingPortal(orgId);location.href=r.url}catch(e){setMessage((e as Error).message)}}}>Manage invoices and payment method →</button></Shell>}

function Admin({me}:{me:Me}){
 const [data,setData]=useState<any>(),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[form,setForm]=useState({cf_account_id:"",cf_gateway_id:"default",cf_api_token:"",generation_model:"openai/gpt-5.6-luna",embedding_model:"@cf/qwen/qwen3-embedding-0.6b",smtp_host:"",smtp_port:"587",smtp_user:"",smtp_password:"",smtp_from:"",stripe_secret_key:"",stripe_webhook_secret:""});
 useEffect(()=>{api.admin().then(setData).catch(e=>setMessage(e.message))},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy("save");setMessage("");const secretKeys=["cf_api_token","smtp_password","stripe_secret_key","stripe_webhook_secret"],entries=Object.entries(form).filter(([,value])=>value!=="").map(([key,value])=>({key,value,secret:secretKeys.includes(key)}));try{await api.saveSettings(entries);setMessage("Platform settings saved. Secret values remain hidden.")}catch(e){setMessage((e as Error).message)}finally{setBusy("")}};
 const test=async(service:string)=>{setBusy(service);setMessage("");try{await api.testService(service);setMessage(`${service.toUpperCase()} connection works.`)}catch(e){setMessage((e as Error).message)}finally{setBusy("")}};
 return <Shell me={me} active="admin"><header className="page-head"><div><p className="utility">Platform settings</p><h1>Services and credentials</h1></div></header><Notice value={message}/>{me.user.platformRole==="super_admin"&&<form className="panel settings-grid" onSubmit={save}><h2>Service configuration</h2>{Object.entries(form).map(([key,value])=><label key={key}>{key.replaceAll("_"," ")}<input disabled={Boolean(busy)} type={key.includes("token")||key.includes("secret")||key.includes("password")?"password":"text"} value={value} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<button className="button" disabled={Boolean(busy)} aria-busy={busy==="save"}><BusyLabel busy={busy==="save"} label={busy==="save"?"Saving settings…":"Save platform settings"}/></button><div className="test-actions">{["ai","smtp","stripe"].map(s=><button type="button" key={s} disabled={Boolean(busy)} onClick={()=>test(s)}><BusyLabel busy={busy===s} label={busy===s?"Testing…":`Test ${s}`}/></button>)}</div></form>}<div className="admin-columns"><section><h2>Organizations</h2>{data?.organizations?.map((o:any)=><p key={o.id}><strong>{o.name}</strong><span>{o.plan} · {o.subscription_status}</span></p>)}</section><section><h2>Recent jobs</h2>{data?.jobs?.map((j:any)=><p key={j.id}><strong>{j.kind}</strong><span>{j.status} · attempt {j.attempts}</span></p>)}</section></div></Shell>
}

function Settings({me}:{me:Me}){const [currentPassword,setCurrent]=useState(""),[newPassword,setNext]=useState(""),[emailPassword,setEmailPassword]=useState(""),[newEmail,setNewEmail]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState("");const change=async(e:React.FormEvent)=>{e.preventDefault();setBusy("password");try{await api.changePassword(currentPassword,newPassword);setCurrent("");setNext("");setMessage("Password changed. Other sessions were signed out.")}catch(e){setMessage((e as Error).message)}finally{setBusy("")}};const changeEmail=async(e:React.FormEvent)=>{e.preventDefault();setBusy("email");try{const r=await api.changeEmail(emailPassword,newEmail);setEmailPassword("");setNewEmail("");setMessage(r.message)}catch(e){setMessage((e as Error).message)}finally{setBusy("")}};return <Shell me={me} active="settings"><header className="page-head"><div><p className="utility">Your settings</p><h1>{me.user.name}</h1><p>{me.user.email}</p></div></header>{me.user.mustChangePassword&&<Notice value="Change the bootstrap password before inviting customers."/>}<Notice value={message}/><div className="settings-stack"><form className="panel form-grid" onSubmit={changeEmail}><h2>Change email</h2><label>New email<input required disabled={busy==="email"} type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/></label><label>Current password<input required disabled={busy==="email"} type="password" value={emailPassword} onChange={e=>setEmailPassword(e.target.value)}/></label><button className="button" disabled={busy==="email"} aria-busy={busy==="email"}><BusyLabel busy={busy==="email"} label={busy==="email"?"Sending confirmation…":"Change email"}/></button></form><form className="panel form-grid" onSubmit={change}><h2>Change password</h2><label>Current password<input required disabled={busy==="password"} type="password" value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label>New password<input required disabled={busy==="password"} type="password" minLength={10} value={newPassword} onChange={e=>setNext(e.target.value)}/></label><button className="button" disabled={busy==="password"} aria-busy={busy==="password"}><BusyLabel busy={busy==="password"} label={busy==="password"?"Changing password…":"Change password"}/></button></form></div></Shell>}

export function App(){
 const [path,setPath]=useState(location.pathname),[me,setMe]=useState<Me|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{const pop=()=>setPath(location.pathname);addEventListener("popstate",pop);return()=>removeEventListener("popstate",pop)},[]);useEffect(()=>{api.me().then(setMe).catch(()=>setMe(null)).finally(()=>setLoading(false))},[path]);
 useEffect(()=>{if(["/verify-email","/magic-login","/confirm-email"].includes(path)){const token=new URLSearchParams(location.search).get("token");if(token)api.consume(token,path==="/verify-email"?"verify":path==="/confirm-email"?"email_change":"magic").then(()=>location.href=path==="/confirm-email"?"/settings":"/dashboard")}},[path]);
 if(loading)return <main className="loading"><span/><p>Opening SignalDesk…</p></main>;
 if(!me){if(path==="/register")return <Auth mode="register"/>;if(path==="/forgot-password")return <Auth mode="forgot"/>;if(path==="/reset-password")return <Auth mode="reset"/>;return <Auth mode="login"/>}
 if(path.startsWith("/projects/"))return <ProjectView me={me} id={path.split("/")[2]}/>;
 if(path==="/projects")return <Projects me={me}/>;
 if(path==="/billing"){const orgId=new URLSearchParams(location.search).get("organization")||me.organizations[0]?.id,org=me.organizations.find(o=>o.id===orgId);return org?.role==="owner"||me.user.platformRole==="super_admin"?<Billing me={me}/>:<Dashboard me={me}/>}
 if(path==="/admin"&&["super_admin","moderator"].includes(me.user.platformRole))return <Admin me={me}/>;
 if(path==="/settings")return <Settings me={me}/>;
 return <Dashboard me={me}/>;
}
